src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),

]

src/app/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'quiz.views.error_400'
handler403 = 'quiz.views.error_403'
handler404 = 'quiz.views.error_404'
handler500 = 'quiz.views.error_500'

src/accounts/models.py
from django.db import models


from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        permissions = [('view_stats', 'View statistics')]

    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    rating = models.IntegerField(null=False, default=0)

src/quiz/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import User

# Create your models here.
from core.models import BaseModel
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def questions_count(self):
        return self.questions.count()

    def get_best_user(self):
        if not self.results.all():
            return 'No score'
        best_result = self.results.order_by('num_correct_answers').last().num_correct_answers
        leaders = []
        duration = []
        for result in self.results.all():
            if result.num_correct_answers == best_result:
                leaders.append(result.user.first_name)
                duration.append(result.test_duration())

        if len(leaders) == 1:
            return leaders[0]
        else:
            index = duration.index(min(duration))
            return leaders[index]

    def get_best_result(self):
        if not self.results.all():
            return 'No score'
        best_result = self.results.order_by('num_correct_answers').last().num_correct_answers

        return best_result

    def last_run(self):
        return self.results.last().create_date

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):  # BaseModel
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def update_result(self, order_number, question, selected_choices):
        correct_choices = [
            choice.is_correct
            for choice in question.choices.all()
        ]

        correct_answer = True
        for x, y in zip(correct_choices, selected_choices):
            correct_answer &= (x == y)

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number
        if order_number == question.test.questions_count():
            self.state = self.STATE.FINISHED

        self.user.rating += self.points()
        self.user.save()
        self.save()

    def test_duration(self):
        duration = self.write_date - self.create_date
        return duration

    def points(self):

        points = self.num_correct_answers - self.num_incorrect_answers
        if points >= 0:
            return points
        else:
            return 0

    def success_rate(self):
        return round(((self.num_correct_answers / self.test.questions_count()) * 100), 2)

    def failure_rate(self):
        return 100 - round(((self.num_correct_answers / self.test.questions_count()) * 100), 2)

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, fields, forms, Form

from django import forms

from accounts.models import User


class AccountCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
        ]


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'bio',
            'birth_date',
        ]

src/accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
# Create your views here.
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, FormView
# from django.contrib import sett
from django.views.generic.list import MultipleObjectMixin

from accounts.forms import AccountCreateForm, AccountUpdateForm
from accounts.models import User
from quiz.models import Result


class AccountCreateView(CreateView):
    model = User
    template_name = 'registration.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.info(self.request, "New user has just been created!")
        return result


class AccountLoginView(LoginView):
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.info(self.request, f'User {self.request.user} has been successfully logged in!')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def get(self, request, *args, **kwargs):
        result = super().get(request, *args, **kwargs)
        messages.info(self.request, f'User {self.request.user} has been logged out!')
        return result


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('index')
    paginate_by = 5

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        return context

    def get_queryset(self):
        return Result.objects.all().select_related('test')


class AccountPasswordUpdateView(LoginRequiredMixin, PasswordChangeView):
    model = User
    template_name = 'password.html'
    success_url = reverse_lazy('accounts:login')

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h1> Login as a user </h1>
{% endblock %}

{% block content %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input type="submit" value="Login">
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h1> User has been logged out </h1>
{% endblock %}

{% block content %}
    <a href = "{% url 'index' %}">Home</a>
    <a href = "{% url 'accounts:login' %}">Login</a>
{% endblock %}

src/accounts/templates/password-change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h1> Update Password </h1>
{% endblock %}

{% block content %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}

      <input type="submit" value="Save">
    </form>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <h1> Account update </h1>
{% endblock %}
{% block content %}
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
            <br>
                <div class="media">
                    <div class="img-circle.vert">
                    <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.profile.image.url }}">
                    </div>
        {#        <img class="rounded-circle p-1 m-1" width="300" height="{{ user.profile.image.height }}"  src="{{ user.profile.image.url }}">#}
        {#        <img class="img-circle p-1 m-1"  src="{{ user.profile.image.url }}">#}
                    <div class="media-body  p-3 m-3">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                    <p class="text-secondary">{{ user.email }}</p>

                    {{user_form|crispy}}
          {{profile_form|crispy}}
          <input type="submit" value="Save">
            <a type="button" class="btn btn-dark" href="{% url 'accounts:password' %}">Change password</a>
                    </div>
                                    <br>


                </div>
        <div style="text-align: center; font-size: 33px; font-family: Arial">User score: {{ user.rating }}</div>
        <br>
        <br>
<table class="table table-striped table-hover">
                      <tr>
                        <th>Test</th>
                        <th>Create date</th>
                        <th>Write date</th>
                        <th>Points</th>
                        <th>State</th>
                      </tr>
                            {% for result in object_list %}
                                  <tr>
                                    <td>{{ result.test }}</td>
                                    <td>{{ result.create_date }}</td>
                                    <td>{{ result.write_date }}</td>
                                    <td>{{ result.points }}</td>
                                    <td>{{ result.get_state_display }}</td>
                                  </tr>
                            {% endfor %}
                </table>

    </form>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h1> Account creation </h1>
{% endblock %}

{% block content %}
    <form method='post'>
      {% csrf_token %}
      {{form|crispy}}
      <input type="submit" value="Create">
    </form>
{% endblock %}