src/accounts/urls.py
from django.urls import path

from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordUpdateView,
    AccountUpdateView
)

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordUpdateView.as_view(), name='password'),

]

src/app/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = 'quiz.views.error_400'
handler403 = 'quiz.views.error_403'
handler404 = 'quiz.views.error_404'
handler500 = 'quiz.views.error_500'

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultQuestionView, TestResultCreateView, \
    TestResultDetailsView, UserLeaderboard, TestResultUpdateView, ResultDeleteView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),


    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('leaderboard/', UserLeaderboard.as_view(), name='leaderboard'),
    path('<uuid:uuid>/results/create', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete', ResultDeleteView.as_view(), name='result_delete'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details', TestResultDetailsView.as_view(), name='result_details'),
    # path('<uuid:uuid>/results/<uuid:result_uuid>/questions/<int:order_number>', TestResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next', TestResultQuestionView.as_view(), name='question'),
]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% block title %}
        <title>Quiz</title>
{% endblock %}
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top navbar-expand-lg navbar-dark bg-primary font-weight-bold ">
  <div class="container">

  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'tests:list' %}">Tests<span class="sr-only">(current)</span></a>
      </li>
    </ul>

    <ul class="navbar-nav ">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>

            {%  if user.is_authenticated %}
                <li class="nav-item">
                    <img alt="Profile pic" width="35" height="35" class="rounded-circle" src="{{ user.image.url }}">
                </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                  </li>

            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
            {% endif %}

    </ul>

  </div>
  </div>
</nav>

  <div class="container">
        {% include 'includes/messages.html' %}

        <div class="border rounded text-center p-3 m-3 mb-5 shadow">
            {% block header %}
                <h1>
                    Welcome to Quiz!!!
                </h1>
            {% endblock %}
        </div>

        {% block content %}
        {% endblock %}
  </div>

</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}